[build]
  publish = "public"
  command = "npm run build"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "/etherpad/*"
  to = "https://fnpad.dev.fnopen.com/p/:splat"
  status = 200